# Generated by Django 3.2.8 on 2021-10-20 11:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='long_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='short_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description_1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
